#!/bin/bash
NAME="$1"
CONFIG="$(pwd)"/config
DATA="$(pwd)"/data
if [[ ! -z "$2" ]] ; then
    if [[ -d "$2" ]]; then
	CONFIG="$2";
	echo "Config override:" "$2"
    else 
	echo "Config override directory invalid:" "$2"
    fi
fi
if [[ ! -z "$3" ]] ; then
    if [[ -d "$3" ]]; then
	DATA="$3";
	echo "Data override:" "$3"
    else 
	echo "Data override directory invalid:" "$3"
    fi
fi

sudo docker container stop "$NAME">/dev/null
sudo docker container rm "$NAME">/dev/null
sudo docker build -t "$NAME" .
sudo docker run \
    -d \
    -it \
    --rm \
    --name "$NAME" \
    -p 80:5001 \
    -v "$CONFIG":/app/config \
    -v "$DATA":/app/data  \
         "$NAME"

